use crate::{
    fs, pipe, print, rtc,
    sched::{self, mycpu},
};

pub fn handle() {
    let task = mycpu().get_task().unwrap();
    let tf = task.get_trap_frame().unwrap();
    print!("++ pid: {} svc: {}\n", task.pid, tf.regs[8]);
    tf.regs[0] = match tf.regs[8] {
        17 => fs::getcwd(),
        24 => fs::dup3(),
        25 => fs::fcntl(),
        29 => fs::ioctl(),
        34 => fs::mkdirat(),
        35 => fs::unlinkat(),
        36 => fs::symlinkat(),
        37 => fs::linkat(),
        38 => fs::renameat(),
        46 => fs::ftruncate(),
        48 => fs::faccessat(),
        49 => fs::chdir(),
        56 => fs::openat(),
        57 => fs::close(),
        59 => pipe::pipe2(),
        61 => fs::getdents64(),
        62 => fs::lseek(),
        63 => fs::sys_read(),
        64 => fs::sys_write(),
        66 => fs::sys_writev(),
        71 => fs::sendfile64(),
        73 => fs::ppoll(),
        78 => fs::readlinkat(),
        79 => fs::newfsstatat(),
        80 => fs::newfstat(),
        88 => fs::utimensat(),
        94 => sched::exit_group(),
        96 => sched::settid(),
        99 => sched::set_robust_list(),
        113 => rtc::clock_gettime(),
        115 => rtc::clock_nanosleep(),
        129 => sched::kill(),
        131 => sched::tgkill(),
        134 => sched::rt_sigaction(),
        135 => sched::rt_sigprocmask(),
        144 => sched::setgid(),
        146 => sched::setuid(),
        154 => sched::setpgid(),
        155 => sched::getgid(),
        160 => sched::uname(),
        166 => fs::umask(),
        174 => sched::getuid(),
        172 => sched::getpid(),
        173 => sched::getppid(),
        175 => sched::geteuid(),
        176 => sched::getgid(),
        178 => sched::gettid(),
        214 => sched::brk(),
        215 => sched::munmap(),
        220 => sched::fork(),
        221 => sched::execve(),
        222 => sched::mmap(),
        226 => sched::mprotect(),
        260 => sched::wait4(),
        261 => sched::prlimit64(),
        278 => fs::getrandom(),
        293 => sched::rseq(),
        // 93 => sched::exit(),
        // 95 => sched::wait(),
        _ => panic!("unimplemented syscall {}\n", tf.regs[8]),
    }
}
